import os
os.system("mkdir InputFiles ");
os.system("eos cp /eos/cms/store/user/rpatel/RA2b/ReducedTree_QCDHT1000.root InputFiles/ReducedTree_QCDHT1000.root")
os.system("eos cp /eos/cms/store/user/rpatel/RA2b/ReducedTree_QCDHT250.root InputFiles/ReducedTree_QCDHT250.root")
os.system("eos cp /eos/cms/store/user/rpatel/RA2b/ReducedTree_QCDHT500.root InputFiles/ReducedTree_QCDHT500.root")
os.system("eos cp /eos/cms/store/user/rpatel/RA2b/ReducedTree_SMSbbbbM1000.root InputFiles/ReducedTree_SMSbbbbM1000.root")
os.system("eos cp /eos/cms/store/user/rpatel/RA2b/ReducedTree_SMSbbbbM1500.root InputFiles/ReducedTree_SMSbbbbM1500.root")
os.system("eos cp /eos/cms/store/user/rpatel/RA2b/ReducedTree_SMSqqqqM1000.root InputFiles/ReducedTree_SMSqqqqM1000.root")
os.system("eos cp /eos/cms/store/user/rpatel/RA2b/ReducedTree_SMSqqqqM1400.root InputFiles/ReducedTree_SMSqqqqM1400.root")
os.system("eos cp /eos/cms/store/user/rpatel/RA2b/ReducedTree_SMSttttM1200.root InputFiles/ReducedTree_SMSttttM1200.root")
os.system("eos cp /eos/cms/store/user/rpatel/RA2b/ReducedTree_SMSttttM1500.root InputFiles/ReducedTree_SMSttttM1500.root")
os.system("eos cp /eos/cms/store/user/rpatel/RA2b/ReducedTree_TBarToLeptons_t.root InputFiles/ReducedTree_TBarToLeptons_t.root")
os.system("eos cp /eos/cms/store/user/rpatel/RA2b/ReducedTree_TTJetsMSDecaysCKM.root InputFiles/ReducedTree_TTJetsMSDecaysCKM.root")
os.system("eos cp /eos/cms/store/user/rpatel/RA2b/ReducedTree_TToLeptons_t.root InputFiles/ReducedTree_TToLeptons_t.root")
os.system("eos cp /eos/cms/store/user/rpatel/RA2b/ReducedTree_T_tW.root InputFiles/ReducedTree_T_tW.root")
os.system("eos cp /eos/cms/store/user/rpatel/RA2b/ReducedTree_Tbar_tW.root InputFiles/ReducedTree_Tbar_tW.root")
os.system("eos cp /eos/cms/store/user/rpatel/RA2b/ReducedTree_WJ100.root InputFiles/ReducedTree_WJ100.root")
os.system("eos cp /eos/cms/store/user/rpatel/RA2b/ReducedTree_WJ200.root InputFiles/ReducedTree_WJ200.root")
os.system("eos cp /eos/cms/store/user/rpatel/RA2b/ReducedTree_WJ400.root InputFiles/ReducedTree_WJ400.root")
os.system("eos cp /eos/cms/store/user/rpatel/RA2b/ReducedTree_WJ600Merged.root InputFiles/ReducedTree_WJ600Merged.root")
os.system("eos cp /eos/cms/store/user/rpatel/RA2b/ReducedTree_ZInv100.root InputFiles/ReducedTree_ZInv100.root")
os.system("eos cp /eos/cms/store/user/rpatel/RA2b/ReducedTree_ZInv200.root InputFiles/ReducedTree_ZInv200.root")
os.system("eos cp /eos/cms/store/user/rpatel/RA2b/ReducedTree_ZInv400.root InputFiles/ReducedTree_ZInv400.root")
os.system("eos cp /eos/cms/store/user/rpatel/RA2b/ReducedTree_ZInv600.root InputFiles/ReducedTree_ZInv600.root")
